services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - 8080:8080       # Web UI port
      - 58261:58261     # BitTorrent port. Needs port forwarding to be setup on the router.
      - 58261:58261/udp # BitTorrent port. Needs port forwarding to be setup on the router.
    environment:
      PUID: 991
      PGID: 994
      UMASK: 002
      TZ: Europe/London
    labels:
      traefik.enable: true
      traefik.http.services.qbittorrent.loadbalancer.server.port: 8080
      traefik.http.routers.qbittorrent.rule: Host(`qbittorrent`)
      traefik.http.routers.qbittorrent.middlewares: trusted-ipallowlist
    volumes:
      - /containers/qbittorrent:/config
      - /downloads:/downloads

networks:
  default:
    enable_ipv6: true
