version: '3'

services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: ${CONTAINER_NAME:-qbittorrent}
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-Europe/London}
      WEBUI_PORT: ${WEBUI_PORT:-8080} # Needs to be set in qBittorrent settings
    volumes:
      - data:/config
      - ${DOWNLOAD_VOLUME:-/downloads}:${DOWNLOAD_VOLUME:-/downloads} # Needs to be set in qBittorrent settings
    ports:
      - ${WEBUI_PORT:-8080}:${WEBUI_PORT:-8080}
      - ${BITTORRENT_PORT:-58261}:${BITTORRENT_PORT:-58261}     # Needs port forwarding to be setup on the router
      - ${BITTORRENT_PORT:-58261}:${BITTORRENT_PORT:-58261}/udp # Needs port forwarding to be setup on the router
    restart: unless-stopped

volumes:
  data:
