services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: host
    environment:
      PUID: 991
      PGID: 994
      UMASK: 002
      TZ: Europe/London
    labels:
      traefik.enable: true
      traefik.http.services.qbittorrent.loadbalancer.server.port: 8080
      traefik.http.routers.qbittorrent.rule: Host(`qbittorrent`)
      traefik.http.routers.qbittorrent.middlewares: qbittorrent-ipallowlist
      traefik.http.middlewares.qbittorrent-ipallowlist.ipallowlist.sourcerange: >
        2a00:23c8:bda0:b310::/64,
        10.10.0.0/16
    volumes:
      - /containers/qbittorrent:/config
      - /downloads:/downloads
