version: '3'

services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: host
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Europe/London
    volumes:
      - /tank/containers/qbittorrent:/config
      - /tank/downloads:/tank/downloads
      - /tank/media/movies:/tank/media/movies
      - /tank/media/tv:/tank/media/tv
      - /tank/media/music:/tank/media/music
      - /tank/media/xxx:/tank/media/xxx
