version: '3'

services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Europe/London
    volumes:
      - data:/config
      - /tank/downloads:/tank/downloads
    ports:
      - 8080:8080       # Web UI port
      - 58261:58261     # BitTorrent port
      - 58261:58261/udp # Needs port forwarding to be setup on the router
    restart: unless-stopped

volumes:
  data:
