services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: host
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: Europe/London
    labels:
      traefik.enable: true
      traefik.http.services.qbittorrent.loadbalancer.server.port: 8080
      traefik.http.routers.qbittorrent.rule: Host(`qbittorrent`)
    volumes:
      - /containers/qbittorrent:/config
      - /downloads:/downloads
      - /tank/media/movies:/tank/media/movies
      - /tank/media/tv:/tank/media/tv
      - /tank/media/music:/tank/media/music
